---
abstract: 'Release tests for version numbers'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.31
generated_by: 'Dist::Zilla version 2.100960'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-HasVersionTests
provides:
  Dist::Zilla::Plugin::HasVersionTests:
    file: lib/Dist/Zilla/Plugin/HasVersionTests.pm
    version: 1.101420
recommends: {}
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Moose: 0
  Test::HasVersion: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-HasVersionTests
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-HasVersionTests/
  repository: http://github.com/hanekomu/Dist-Zilla-Plugin-HasVersionTests
version: 1.101420
